buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://files.minecraftforge.net/maven' }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'maven-publish'

version = "v${mod_version}-mc1.12.2"
group = 'git.jbredwards.campfire'
archivesBaseName = 'Campfire'
sourceCompatibility = targetCompatibility = '1.8'

minecraft {
    version = "1.12.2-14.23.5.2847"
    runDir = "run"
    mappings = "stable_39"
    makeObfSourceJar = false
}

dependencies {
    // blamejared
    deobfProvided 'com.teamacronymcoders:ContentTweaker:1.12.2-4.10.0-Snapshot.30'
    deobfProvided "CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-4.1.20.700"
    deobfProvided 'vazkii.autoreglib:AutoRegLib:1.3-32.+'
    deobfProvided 'vazkii.quark:Quark:r1.6-180.7'
    // cleanroom
    deobfCompile 'com.cleanroommc:assetmover:2.5'
    // curseforge repos
    deobfProvided 'ex-nihilo-creatio:exnihilocreatio:1.12:0.3.2'
    deobfProvided 'albedo:albedo:1.12.2:1.1.0'
    deobfProvided 'nuclearcraft-mod:nuclearcraft:1.12.2:2.19'
    // modmaven
    deobfCompile "mezz.jei:jei_1.12.2:${jei_version}"
    deobfProvided 'slimeknights.mantle:Mantle:1.12-1.3.3.55'
    deobfProvided 'slimeknights:TConstruct:1.12.2-2.13.0.184'
    //tterrag
    // deobfProvided 'mcjty.theoneprobe:TheOneProbe-1.12:1.12-1.4.28-17'
    // modrinth repos
    deobfCompile "maven.modrinth:hwyla:${hwyla_version}"
    deobfProvided "maven.modrinth:fluidlogged-api:${fluidlogged_api_version}"
    deobfProvided "maven.modrinth:future-mc:${future_mc_version}"
    deobfProvided "maven.modrinth:groovyscript:${groovyscript_version}"
    deobfProvided "maven.modrinth:piston-api:${piston_api_version}"
}

repositories {
    maven { url 'https://api.modrinth.com/maven' }
    maven { url 'https://maven.blamejared.com' }
    maven { url 'https://maven.cleanroommc.com' }
    maven { url 'https://maven.shadowfacts.net' }
    // maven { url 'https://maven.tehnut.info' }
    // maven { url 'https://maven.tterrag.com' }
    maven { url 'https://minecraft.curseforge.com/api/maven' }
    maven {
        name = 'DVS1 Maven FS'
        url = 'https://dvs1.progwml6.com/files/maven'
    }
}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version
    inputs.property "mod_version", project.mod_version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':project.minecraft.version, 'mod_version':project.mod_version
    }
        
    // copy everything else except the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

task deobfJar(type: Jar) {
    from sourceSets.main.output
    classifier = 'deobf'
}

task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    classifier = 'sources'
}

artifacts {
    archives deobfJar
    archives sourcesJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
            artifact deobfJar
            artifact sourcesJar
        }
    }
}

//for applying asm outside dev environment
jar {
    manifest {
        attributes(
                'FMLCorePlugin': 'git.jbredwards.campfire.mod.asm.ASMHandler',
                'FMLCorePluginContainsFMLMod': 'true',
                'FMLAT':'campfire_at.cfg'
        )
    }
}

//for applying asm with intellij
runClient { jvmArgs '-Dfml.coreMods.load=git.jbredwards.campfire.mod.asm.ASMHandler' }
runServer { jvmArgs '-Dfml.coreMods.load=git.jbredwards.campfire.mod.asm.ASMHandler' }