# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
mod_version=2.0.0

fluidlogged_api_version=y52dPt4Z
future_mc_version=DHdJ5LFT
groovyscript_version=Slez34pS
piston_api_version=qWE35ybh
hwyla_version=pgcAdhbb
jei_version=4.15.0.268
