/*
 * Copyright (c) 2024. jbredwards
 * All rights reserved.
 */

package git.jbredwards.campfire.api.registry;

import net.minecraftforge.fml.common.ModContainer;
import net.minecraftforge.fml.common.eventhandler.EventPriority;
import net.minecraftforge.registries.IForgeRegistryEntry;

import javax.annotation.Nonnull;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.util.function.Consumer;

/**
 *
 * @since 2.0.0
 * @author jbred
 *
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface RegistryContainer
{
    /**
     * See {@link net.minecraftforge.registries.GameData GameData} for the list of forge & vanilla registry ids.
     * If this is left empty, all entries and actions in this container are ignored.
     * @return The registry id for this container to register its entries to. May be empty.
     *
     * @since 2.0.0
     * @author jbred
     */
    @Nonnull
    Class<? extends IForgeRegistryEntry>[] value() default {};

    /**
     * This only needs to be specified if your mod has a custom {@link ModContainer} implementation,
     * or if it uses one that does not properly implement {@link ModContainer#getOwnedPackages()}.
     * @return The owning mod for this container if specified, or autogenerated if possible.
     *
     * @since 2.0.0
     * @author jbred
     */
    @Nonnull
    String modid() default "";

    @Nonnull
    String[] dependencies() default {};

    /**
     * @return True for this container to subscribe to the {@link net.minecraftforge.common.MinecraftForge#EVENT_BUS MinecraftForge.EVENT_BUS}.
     *
     * @since 2.0.0
     * @author jbred
     */
    boolean hasEvents() default false;

    /**
     * @return The priority this container should have.
     *
     * @since 2.0.0
     * @author jbred
     */
    @Nonnull
    EventPriority priority() default EventPriority.NORMAL;

    /**
     *
     * @since 2.0.0
     * @author jbred
     *
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.RUNTIME)
    @interface Action
    {
        /**
         * @return The priority this action should have.
         *
         * @since 2.0.0
         * @author jbred
         */
        @Nonnull
        EventPriority priority() default EventPriority.NORMAL;
    }

    /**
     *
     *
     * @since 2.0.0
     * @author jbred
     *
     */
    @Nonnull
    @Target(ElementType.FIELD)
    @Retention(RetentionPolicy.RUNTIME)
    @interface Entry
    {
        /**
         * If this is left empty, a registry id will attempt to be generated at runtime (depending on this entry's registry type).
         * @return The registry name of this object. The mod id is determined automatically, and does not need to be specified here.
         *
         * @since 2.0.0
         * @author jbred
         */
        @Nonnull
        String value() default "";
    }

    /**
     *
     * @since 2.0.0
     * @author jbred
     *
     */
    final class Helper
    {
        /**
         * Performs an action on the given registry entry.
         *
         * @param entry Registry entry argument.
         * @param action The action to perform.
         * @return The provided registry entry.
         *
         * @throws NullPointerException If entry or action are null.
         * @since 2.0.0
         * @author jbred
         */
        @Nonnull
        public static <T> T create(@Nonnull final T entry, @Nonnull final Consumer<T> action) {
            action.accept(entry);
            return entry;
        }
    }
}
